### ISSUE TITLE
Certificates in oneprovider are not loaded in RC-4

### ISSUE THREAD

**Issue by bwegh** [indigo-dc/onedata#1]
The oneprovider starts and is up, also seems to connect to the onezone,
yet when trying to connect to onepanel at port 9443 not the added certificates are used.
Instead a self-signed certificates issued for onepanel.com are used:

```
one.data.kit.edu:9443 uses an invalid security certificate. 
The certificate is not trusted because it is self-signed. 
The certificate is only valid for onepanel.com 

The certificate expired on 30/07/14 18:06. 
The current time is 07/09/16 13:41. 
Error code: SEC_ERROR_UNKNOWN_ISSUER
```

the configuration, the script to run oneprovider and all the git versions are in the attached log file

[oneprovider_log.txt](https://github.com/indigo-dc/onedata/files/458973/oneprovider_log.txt)

**Comment by groundnuty** [comment]
Please change the line:
"/home/bas/.config/onedata/certs/onedataServerFuse.pem:/volumes/persistence/etc/op_worker/onedataServerFuse.pem"
to
"/home/bas/.config/onedata/certs/onedataServerFuse.pem:/volumes/persistence/etc/op_worker/certs/onedataServerFuse.pem"

There seems to be an error in the documentation.  Please try and report back :)

**Comment by bwegh** [comment]
same issue:
```
one.data.kit.edu:9443 uses an invalid security certificate. 
The certificate is not trusted because it is self-signed. 
The certificate is only valid for onepanel.com The certificate expired on 30/07/14 18:06. 
The current time is 07/09/16 14:55. 
Error code: SEC_ERROR_UNKNOWN_ISSUER
```
[oneprovider_log.txt](https://github.com/indigo-dc/onedata/files/459140/oneprovider_log.txt)

**Comment by bwegh** [comment]
still the same issue:

```
one.data.kit.edu:9443 uses an invalid security certificate. 
The certificate is not trusted because it is self-signed. 
The certificate is only valid for onepanel.com The certificate expired on 30/07/14 18:06. 
The current time is 07/09/16 15:09. 
Error code: SEC_ERROR_UNKNOWN_ISSUER
```

[oneprovider_log.txt](https://github.com/indigo-dc/onedata/files/459163/oneprovider_log.txt)

**Comment by groundnuty** [comment]
@bwegh 
I've commited few examples paths thare are known to be working in our production installation. There seems to be a change in certificate management in rc5 that I was not aware of.

Please use branch release/rc5 instead of master for now and inspect that commit:
https://github.com/onedata/getting-started/commit/c2e7ecbe9eb6b08e09938a21760f32490f858d88

Hope that helps.
