### ISSUE TITLE
rc11 does not start

### ISSUE THREAD

**Issue by bwegh** [indigo-dc/onedata#14]
```
Configuring oneprovider:
* service_couchbase: configure
* service_couchbase: start
* service_couchbase: wait_for_init
* service_couchbase: init_cluster
* service_couchbase: rebalance_cluster
* service_couchbase: status
* service: save
* service_cluster_manager: configure
* service_cluster_manager: stop
* service_cluster_manager: start
* service_cluster_manager: status
* service_op_worker: configure
* service_op_worker: setup_certs
* service_op_worker: stop
* service_op_worker: start

Error: Service Error
Description: Action 'deploy' for a service 'oneprovider' terminated with an error.
Module: service_op_worker
Function: start
Hosts: node1.oneprovider.localhost
For more information please check the logs.
oneprovider_kit exited with code 1
```

attached all logs 
[latest.zip](https://github.com/indigo-dc/onedata/files/623857/latest.zip)

**Comment by groundnuty** [comment]
need op_panel logs

**Comment by bwegh** [comment]
see zip file attached in original message

**Comment by bwegh** [comment]
any updates on this?

**Comment by groundnuty** [comment]
Dear @bwegh 
Appologies for long resonse time. Logs suggest that there is a problem with op worker cert. Please adjust your docker compose so the volumes resemble this compose:
https://github.com/onedata/getting-started/blob/master/scenarios/3_0_oneprovider_onezone_multihost/docker-compose-oneprovider.yml#L19
The only op_worker cert that is needed is in the line L19 and its the same that is needed for *op_panel/cacerts/cacert.pem* (hence the same variables in lines L18 and L19)

Michal

**Comment by bwegh** [comment]
@groundnuty happy new year :)
I tried again, yet still no luck, see attached logs
[oneprovider_20170111_112722.zip](https://github.com/indigo-dc/onedata/files/698430/oneprovider_20170111_112722.zip)
