### ISSUE TITLE
rc11 files synchronization not working

### ISSUE THREAD

**Issue by evasciacca** [indigo-dc/onedata#15]
Dear all, 

I was able to deploy rc11 OneZone and two OneProviders and I am having problems on testing it because uploaded data into a space (supported by the two providers) are not getting synchronized. I send you attached all the log files. Please let me know if you need more details to understand the problem. 

Thank you in advance,

Eva.

[rc11_log_files.zip](https://github.com/indigo-dc/onedata/files/702158/rc11_log_files.zip)

**Comment by groundnuty** [comment]
Dear Eva,
Could you please answer those questions to help us narrow down the issues:
Having a space in question and data uploaded to it.
1) You can see all your data on one of the providers, or on none?
2) You see data on both providers, but just partially?

Michal

**Comment by evasciacca** [comment]
Dear Michal,

Here the answers:

> You can see all your data on one of the providers, or on none?
> You see data on both providers, but just partially?

I can see that one file has been synchronized in both providers (from distribution button) but another one is only on the provider (provider_2) where I have uploaded the file (and a loading rotating image keeps appearing, maybe indicating that something is still under processing...)

Eva.

**Comment by groundnuty** [comment]
Another question,
what are the parameters of your machines? The logs suggested that 90% of
RAM is filled.

Michal.

**Comment by evasciacca** [comment]
Dear Michal,

I was using 4 GB for the RAM (it was enough for the other tests using rc9). Then I will try to increase and test it again, thank you for the suggestion. By the way, which logs should I have to look in particular to find out this kind of issues?

Eva.

**Comment by evasciacca** [comment]
Yes, now I enlarged the RAM to 8 GB and files get synchronized but the loading circle icon keeps appearing any time I click on a file into a space. Do you suggest to enlarge it even more (I am running zone + 2 providers on the same VM for these tests) ?

Eva.

**Comment by groundnuty** [comment]
If tools like top or htop, suggest that the RAM is full then yes.
In order to assist you effectively, I think, it would be faster to support
if I would have access that that machine. Please consider adding our
support key (send me an email to orzechowski.michal@cyfronet.pl, and I will
send you the key).

**Comment by evasciacca** [comment]
Dear Michal,

thank you for your availability but I think we have now solved the issue by increasing the number of CPU cores as well.

Thank you for your support,

Eva.

**Comment by groundnuty** [comment]
Dear Eva,
Glad to hear it, if any other problems arise, please don't hesitate to contact us here. For now, I mark this issue as resolved.
Michal
