### ISSUE TITLE
Use of Roles/Permissions

### ISSUE THREAD

**Issue by evasciacca** [indigo-dc/onedata#21]
We would like to understand how to map groups coming from the INDIGO-IAM to roles and permissions on datasets contained into a space.

**Comment by xorver** [comment]
We are going to automatically add indigo groups as onedata groups, on the basis of information given by INDIGO-IAM. We expect this feature to be ready by the end of June, but it requires cooperation with external teams so I can't tell for sure if it won't be slightly delayed.

**Comment by evasciacca** [comment]
Great! Thanks, please update us on this integration.
Cheers,
Eva.

**Comment by andreaceccanti** [comment]
@xorver, feel free to contact me anytime for doubts/questions related to IAM groups

**Comment by groundnuty** [comment]
@evasciacca this feature is live as of 17.06.0-beta6 :)
