### ISSUE TITLE
[Feature request] Access token to mount single onedata space

### ISSUE THREAD

**Issue by mtangaro** [indigo-dc/onedata#22]
Dear Onedata developers,
As discussed during the INDIGO-Summit for the ELIXIR-ITALY use case we need to mount just one single space at time, using oneclient or onedata REST APIs.
 
We currently mount  onedata spaces, through oneclient, using it as the default storage area. 
We would store only Galaxy analysis input and output files on onedata.
 
The problem is that if an user has more than one space, each one corresponding to a different galaxy instance (or worse storing personal files), all of them will be mounted at the same time.
Since Galaxy can be used to analyze sensitive data (and the possibility to use Galaxy in clinical scenarios is one of  the defining features of our use case), we have to avoid this.
Moreover, we are using onedata also to ship reference rata, which are the same for many bioinformatics analysis, and in that case they can and should be shared among different users.
On the contrary, I don't want to share my user-data files (or I want to choose  which spaces have to be shared on more than one VMs), because within the space I have my personal, still not public, analysis results.
 
**Summary: the user has to be able to select which of his/her one data spaces have to be mounted and their sharing policy (public or private).**
 
Currently, when I get the access token, I'm mounting all my spaces.
 
Thanks a lot for your help.
Best Regards,
Marco.

**Comment by groundnuty** [comment]
This feature is on our TODO list we are aware of its importance, please bear with us. As far as I know it will not appear in the newest `17.06.0` release.
