### ISSUE TITLE
Error removing directories

### ISSUE THREAD

**Issue by mtangaro** [indigo-dc/onedata#24]
Dear Onedata experts,
For the ELIXIR-ITALY use case we are using a onedata space to store Galaxy input and output data. To do that Galaxy creates a directory named “database” to store all of them. But I'm experiencing some difficulties to remove directories from my space, once created:
 
onedata space mountpoint: /data
ondata space name: galaxy
 
(.venv) [galaxy@galaxy-test galaxy]$ ls
ciao.txt  _conda  database  job_work  prova  tool_deps
(.venv) [galaxy@galaxy-test galaxy]$ rm -rf _conda
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/weakref.py’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/wsgiref’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/xml/dom/expatbuilder.py’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/xml/dom/minicompat.py’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/xml/sax/__init__.py’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/xmlrpc/__pycache__/__init__.cpython-35.opt-2.pyc’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/lib2to3/fixes/__pycache__/fix_ne.cpython-35.pyc’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/lib2to3/fixes/__pycache__/fix_urllib.cpython-35.pyc’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/lib2to3/fixes/__pycache__/fix_next.cpython-35.opt-1.pyc’: Resource temporarily unavailable
rm: cannot remove ‘_conda/pkgs/python-3.5.2-0/lib/python3.5/lib2to3/fixes/__pycache__/fix_renames.cpython-35.pyc’: Resource temporarily unavailable
…
 
trying to remove it on the web interface give me:
"_conda" could not be removed: Internal Sever Error
 
These directories has been created automatically by galaxy. While if I manually create directories I can remove them.
I don’t know if this is related only to the oneprovider that I’m using (indigo-wp3-onep.recas.ba.infn.it), we are investigating this issue.
Thanks a lot
Marco.

**Comment by luman75** [comment]
@mtangaro on which version of oneclient are you working?
