### ISSUE TITLE
Permission denied using REST API

### ISSUE THREAD

**Issue by ferag** [indigo-dc/onedata#25]
Dear developers,

I'm getting a permission_denied error when I try to create a new index from metadata, following the documentation. The command I'm using is:

curl --tlsv1.2 -X POST -H "X-Auth-Token: $ONE_DATA_TOKEN" -H 'Content-type: application/javascript' -d @title_index.js "https://$ONE_DATA_HOST:8443/api/v3/oneprovider/index?space_id=$ONE_DATA_SPACE_ID&name=title_index"

And the trace of the error:

*   Trying 90.147.102.84...
* Connected to oneprovider2.cloud.ba.infn.it (90.147.102.84) port 8443 (#0)
* found 173 certificates in /etc/ssl/certs/ca-certificates.crt
* found 697 certificates in /etc/ssl/certs
* ALPN, offering http/1.1
* SSL connection using TLS1.2 / ECDHE_RSA_AES_128_GCM_SHA256
* 	 server certificate verification OK
* 	 server certificate status verification SKIPPED
* 	 common name: oneprovider2.cloud.ba.infn.it (matched)
* 	 server certificate expiration date OK
* 	 server certificate activation date OK
* 	 certificate public key: RSA
* 	 certificate version: #3
* 	 subject: DC=org,DC=terena,DC=tcs,C=IT,ST=Rome,L=Frascati,O=Istituto Nazionale di Fisica Nucleare,CN=oneprovider2.cloud.ba.infn.it
* 	 start date: Thu, 07 Jul 2016 00:00:00 GMT
* 	 expire date: Sun, 06 Aug 2017 12:00:00 GMT
* 	 issuer: C=NL,ST=Noord-Holland,L=Amsterdam,O=TERENA,CN=TERENA eScience SSL CA 3
* 	 compression: NULL
* ALPN, server did not agree to a protocol
> POST /api/v3/oneprovider/index?space_id=Lifewatch&name=title_index HTTP/1.1
> Host: oneprovider2.cloud.ba.infn.it:8443
> User-Agent: curl/7.47.0
> Accept: */*
> X-Auth-Token: (HIDDEN)
> Content-type: application/javascript
> Content-Length: 90
> 
* upload completely sent off: 90 out of 90 bytes
< HTTP/1.1 403 Forbidden
< connection: close
< server: Cowboy
< date: Thu, 06 Jul 2017 08:32:16 GMT
< content-length: 70
< content-type: application/json
< 
* Closing connection 0
{"error_description":"Permission denied.","error":"permission_denied"}

Is there any thing in the server that must to be enabled?

Maybe Stefano could add more info...

Thank you,

Fernando

**Comment by ferag** [comment]
Hi again,

Any kind of answer?
Thanks,
Fernando

**Comment by groundnuty** [comment]
@ferag as far as I know this particular issue was resolved in the newest release `17.06.0-beta6` please test it against the newest version and reopen this ticket if needed.
