### ISSUE TITLE
RC6 fails to start with customised configuration

### ISSUE THREAD

**Issue by stefanonicotri** [indigo-dc/onedata#3]
starting the onezone (scenario 3_0 multihost) with the command `./run_onedata.sh --zone` it fails with the following error message:

<pre>
onezone-1                  | * service_onepanel: create_tables
onezone-1                  | Error: Service Error
onezone-1                  | Description: Action 'deploy' for a service 'onezone' terminated with an error.
onezone-1                  | Module: service_onepanel
onezone-1                  | Function: create_tables
onezone-1                  | Hosts: onezone.cloud.ba.infn.it
</pre>

the differences between the original docker-compose file and the customised ones are the following:

<pre>
7c7
<     hostname: onezone.cloud.ba.infn.it

---
>     hostname: node1.onezone.localhost
16c16
<         - "/opt/onedata/onezone/auth.conf:/volumes/persistence/var/lib/oz_worker/auth.config"

---
>         #- "${AUTH_PATH}:/volumes/persistence/var/lib/oz_worker/auth.config"
20,22c20,22
<         - "/opt/onedata/onezone/ssl/etc/oz_worker/certs/gui_key.pem:/volumes/persistence/etc/oz_panel/certs/key.pem"
<         - "/opt/onedata/onezone/ssl/etc/oz_worker/certs/gui_cert.pem:/volumes/persistence/etc/oz_panel/certs/cert.pem"
<         - "/opt/onedata/onezone/ssl/etc/oz_worker/cacerts/gui_cacert.pem:/volumes/persistence/etc/oz_panel/certs/cacert.pem"

---
>         #- "${OZ_PRIV_KEY_PATH}:/volumes/persistence/etc/oz_panel/certs/key.pem"
>         #- "${OZ_CERT_PATH}:/volumes/persistence/etc/oz_panel/certs/cert.pem"
>         #- "${OZ_CACERT_PATH}:/volumes/persistence/etc/oz_panel/certs/cacert.pem"
41c41
<           domainName: "cloud.ba.infn.it"

---
>           domainName: "onezone.localhost"
45c45
<               hostname: "onezone"

---
>               hostname: "node1"
57,58c57,58
<           name: "INFN-BA"
<           domainName: "onezone.cloud.ba.infn.it"

---
>           name: "Example"
>           domainName: "onezone.localhost"
</pre>

**Comment by groundnuty** [comment]
as we managed to run onezoen on the same machine with version rc9, I consider that issue closed.
