### ISSUE TITLE
rc9 change admin password

### ISSUE THREAD

**Issue by aleita** [indigo-dc/onedata#4]
Trying to change the default password using the web interface fails for the following reason:
- Cannot change password due to an error:   Cannot change user password - old password incorrect.

but using the same password I successfully logged in in order to try to change it.

Ale

**Comment by groundnuty** [comment]
we'r looking into that...

**Comment by aleita** [comment]
just to say that changing the user password via REST API works fine

curl -v -Ssk -u admin:password -H "Content-type: application/json" -X PATCH -d '{"password": "new_password"}'  https://onezone.cloud.ba.infn.it:9443/api/v3/onepanel/users/admin/

**Comment by groundnuty** [comment]
@aleita in progress in rc10

**Comment by kliput** [comment]
Fixed in development by @lopiola . The fix will be included in rc10.
