### ISSUE TITLE
rc9 null space name breaks  spaces registration procedure on the oneprovider

### ISSUE THREAD

**Issue by aleita** [indigo-dc/onedata#5]
We have experienced a serious issue after 
we tried to registered a space with null name on the oneprovider

No more space could be registered on that oneprovider.

**Comment by groundnuty** [comment]
we will add validation in rc10 for that.
also I believe it just affects one user not the whole provider, can you confirm?

the fix is to use erlang console to rename all the null spces to a proper name.
we did that yesterday for your provider. are you still experiencing issues?

**Comment by aleita** [comment]
This is what I've seen

after I tried to enable a user space with null name
every time I tried to access oneprovider admin spaces page I got the same error

"There has been an error in comet process. Please refresh the page."

and the list of all the already registered spaces were not displayed.
at the same time I was not able to register a new space anymore.

after deleting from onezone all the spaces with null name everything came back to work as usually and I could access the oneprovider space admin page

Ale

**Comment by groundnuty** [comment]
@aleita in progress in rc10

**Comment by kliput** [comment]
@groundnuty @aleita Fixed in development version. The fix will be included in rc10.
