### ISSUE TITLE
Oneprovider rc9 Ceph storage

### ISSUE THREAD

**Issue by stanislaw-jankowski-sonatus** [indigo-dc/onedata#9]
I am trying to add CEPH storage to OneProvider using OnePanel.
Unfortunately I got errors - see attached error log.
Maybe it is simple firewall issue - official documentation (https://onedata.org/docs/doc/administering_onedata/storage_configuration.html) does not say anything which ports should be open between CEPH node and OneProvider.
[oneprovider_ceph_errors.txt](https://github.com/indigo-dc/onedata/files/552909/oneprovider_ceph_errors.txt)

**Comment by groundnuty** [comment]
@sarevok 
we need to access your machine and investigate your CEPH storage. It is difficult to say anything at this point...

For more secured communication: michal.orzechowski@cyfronet.pl :)

**Comment by groundnuty** [comment]
the ceph problems were resolved in new rc14 version.
